# Evaluation

- dataset:Ering (full dataset)
- clustering: dbscan
- max_iter: 20
- frameworks: MOSCAT, EvolClustering, Baseline

The authors of EvolClustering suggest to set $w=0.1$ in their solution, so we did this. In case of MOSCAT, we utilized TOPSIS to select the weight, because it is a simple non-parametric method.
We defined the baseline as clustering without temporal context.

## Full Set of Solutions

In [1]:
import pandas as pd
import os
import math
import numpy as np

evaluation_df=pd.read_csv(os.getcwd()+'/stats/evaluation_result.csv')
pd.set_option("display.max_rows", None)
#evaluation_df.query('method=="moscat" | method=="baseline"')
evaluation_df.sort_values(by=['w'])
evaluation_df['av_sq']=evaluation_df['av_sq']/2
evaluation_df

,method,w,av_c_num,std_c_num,av_sq,std_sq,av_tq,std_tq,av_total_score,av_purity,std_purity
0,baseline,0.0,2.076923,0.321505,0.360655,0.022743,0.551385,0.325389,0.636347,0.190564,0.057899
1,moscat,0.0,3.507692,0.953990,0.253962,0.099357,0.732769,0.201359,0.620346,0.380718,0.082453
2,moscat,0.1,3.507692,0.953990,0.253962,0.099357,0.732769,0.201359,0.620346,0.380718,0.082453
3,moscat,0.2,3.507692,0.953990,0.253962,0.099357,0.732769,0.201359,0.620346,0.380718,0.082453
4,moscat,0.3,3.507692,0.953990,0.253962,0.099357,0.732769,0.201359,0.620346,0.380718,0.082453
5,moscat,0.4,3.569231,0.934900,0.257192,0.084394,0.731846,0.201997,0.623115,0.381538,0.081748
6,moscat,0.5,3.569231,0.934900,0.257154,0.084469,0.748154,0.159441,0.631231,0.384923,0.075749
7,moscat,0.6,3.584615,0.950202,0.255269,0.087241,0.758923,0.142501,0.634731,0.386667,0.076870
8,moscat,0.7,3.646154,1.204559,0.236962,0.121997,0.771538,0.134085,0.622731,0.397333,0.081465
9,moscat,0.8,4.000000,2.000000,0.224692,0.132005,0.780769,0.136454,0.615077,0.401077,0.082313
10,moscat,0.9,3.830769,2.058285,0.209077,0.162217,0.785231,0.138791,0.601692,0.401026,0.082851
11,moscat,1.0,4.030769,1.984071,0.222923,0.134657,0.778615,0.139080,0.612231,0.399744,0.084927
12,evol,0.0,2.076923,0.321505,0.360655,0.022743,0.568769,0.301975,0.645040,0.190564,0.057899
13,evol,0.1,2.000000,0.000000,0.357405,0.022374,0.596308,0.231014,0.655559,0.177897,0.005156
14,evol,0.2,2.000000,0.000000,0.354352,0.024043,0.694000,0.196801,0.701352,0.179692,0.004629
15,evol,0.3,2.000000,0.000000,0.354069,0.024084,0.701385,0.186287,0.704762,0.179897,0.004329
16,evol,0.4,2.000000,0.000000,0.354069,0.024084,0.701385,0.186287,0.704762,0.179897,0.004329
17,evol,0.5,2.030769,0.174036,0.352648,0.023155,0.706923,0.182388,0.706110,0.180256,0.004576
18,evol,0.6,2.030769,0.174036,0.352648,0.023155,0.706923,0.182388,0.706110,0.180256,0.004576
19,evol,0.7,2.030769,0.174036,0.352648,0.023155,0.706923,0.182388,0.706110,0.180256,0.004576
20,evol,0.8,2.030769,0.174036,0.352648,0.023155,0.706923,0.182388,0.706110,0.180256,0.004576
21,evol,0.9,2.030769,0.174036,0.352648,0.023155,0.706923,0.182388,0.706110,0.180256,0.004576
22,evol,1.0,2.030769,0.174036,0.352648,0.023155,0.706923,0.182388,0.706110,0.180256,0.004576

## Solution Selection by the Strategies Mentioned Above

In [16]:
def calc_topsis(sq,tq):
    dist_to_max=math.sqrt((sq-2)**2+(tq-2)**2)
    dist_to_min=math.sqrt((sq-0)**2+(tq-0)**2)
    oq=dist_to_min/(dist_to_min+dist_to_max)
    return oq

moscat_results=evaluation_df.query('method=="moscat"').copy()
moscat_results['oq'] = moscat_results.apply(lambda row: calc_topsis(row['av_sq'],row['av_tq']),axis=1)
moscat_results
topsis_max_idx=moscat_results['oq'].idxmax()
topsis_moscat_result=moscat_results.loc[topsis_max_idx]
topsis_moscat_result=pd.DataFrame(topsis_moscat_result).transpose()[['method','w','av_purity','std_purity','av_c_num','std_c_num']]

evol_result = evaluation_df.query('method=="evol" & w==0.1').copy()[['method','w','av_purity','std_purity','av_c_num','std_c_num']]
evol_result
baseline=evaluation_df.query('method=="baseline"').copy()[['method','w','av_purity','std_purity','av_c_num','std_c_num']]
topsis_moscat_result

total_result=pd.concat([topsis_moscat_result,evol_result,baseline])
total_result

      method    w av_purity std_purity  av_c_num std_c_num
9     moscat  0.8  0.401077   0.082313       4.0       2.0
13      evol  0.1  0.177897   0.005156       2.0       0.0
0   baseline  0.0  0.190564   0.057899  2.076923  0.321505